name: Admin Panel CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
     - mainBranch

jobs:

  build:
    name: Build - Continous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Build Admin Panel
        run: npm run build -- --mode production
        env:
          VITE_APP_API_URL: https://backend.ecomm.adriannyc.dev

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: dist

  deploy:
    name: Deploy - Continous Deployment
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/mainBranch'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist